/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.sample;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LoginPage extends javax.swing.JFrame {
    public databaseConnection con;
    /**
     * Creates new form LoginPage
     * @param con
     */
    public LoginPage(databaseConnection con) {
        this.con = con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerback = new javax.swing.JPanel();
        LoginBackground = new javax.swing.JPanel();
        Login_btn = new javax.swing.JButton();
        EmailF = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        errorLabelEmail = new javax.swing.JLabel();
        passIconLabel = new javax.swing.JLabel();
        EmailIconLabel = new javax.swing.JLabel();
        hasAccountLabel = new javax.swing.JLabel();
        LoginFormLabel = new javax.swing.JLabel();
        Register = new javax.swing.JLabel();
        LoginFormLabel1 = new javax.swing.JLabel();
        LOGO = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Background"); // NOI18N
        setResizable(false);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        layerback.setBackground(new java.awt.Color(100, 104, 122));

        LoginBackground.setBackground(new java.awt.Color(51, 51, 51));
        LoginBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        LoginBackground.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                LoginBackgroundAncestorResized(evt);
            }
        });

        Login_btn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        EmailF.setBackground(new java.awt.Color(102, 102, 102));
        EmailF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EmailF.setForeground(new java.awt.Color(184, 184, 184));
        EmailF.setText("Enter your email or username");
        EmailF.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 6, 5, 6, new java.awt.Color(102, 102, 102)));
        EmailF.setCaretPosition(0);
        EmailF.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        EmailF.setDragEnabled(true);
        EmailF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailFMouseClicked(evt);
            }
        });
        EmailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFActionPerformed(evt);
            }
        });
        EmailF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailFKeyTyped(evt);
            }
        });

        passField.setBackground(new java.awt.Color(102, 102, 102));
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setToolTipText("");
        passField.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 6, 5, 7, new java.awt.Color(102, 102, 102)));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });

        errorLabelEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        errorLabelEmail.setForeground(new java.awt.Color(164, 33, 39));
        errorLabelEmail.setText("Incorrect Password or Email");

        passIconLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        passIconLabel.setForeground(new java.awt.Color(184, 184, 184));
        passIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\key.png")); // NOI18N
        passIconLabel.setText("Password:");

        EmailIconLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EmailIconLabel.setForeground(new java.awt.Color(184, 184, 184));
        EmailIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\email.png")); // NOI18N
        EmailIconLabel.setLabelFor(EmailIconLabel);
        EmailIconLabel.setText("Username:");

        hasAccountLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        hasAccountLabel.setForeground(new java.awt.Color(187, 186, 188));
        hasAccountLabel.setText("I don't have an account?");

        LoginFormLabel.setBackground(new java.awt.Color(255, 255, 255));
        LoginFormLabel.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        LoginFormLabel.setForeground(new java.awt.Color(100, 78, 199));
        LoginFormLabel.setText("STYLISHSPEND");
        LoginFormLabel.setMaximumSize(new java.awt.Dimension(38, 16));

        Register.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 51, 102));
        Register.setText("Register");
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
        });

        LoginFormLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        LoginFormLabel1.setForeground(new java.awt.Color(184, 184, 184));
        LoginFormLabel1.setText("LOGIN");
        LoginFormLabel1.setMaximumSize(new java.awt.Dimension(38, 16));

        javax.swing.GroupLayout LoginBackgroundLayout = new javax.swing.GroupLayout(LoginBackground);
        LoginBackground.setLayout(LoginBackgroundLayout);
        LoginBackgroundLayout.setHorizontalGroup(
            LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBackgroundLayout.createSequentialGroup()
                .addGroup(LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginBackgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginFormLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmailIconLabel)
                                .addGroup(LoginBackgroundLayout.createSequentialGroup()
                                    .addComponent(passIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                    .addComponent(errorLabelEmail))
                                .addComponent(passField)
                                .addGroup(LoginBackgroundLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LoginBackgroundLayout.createSequentialGroup()
                                    .addComponent(hasAccountLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Register))
                                .addComponent(EmailF))))
                    .addGroup(LoginBackgroundLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(LoginFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        LoginBackgroundLayout.setVerticalGroup(
            LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LoginFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(LoginFormLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmailIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passIconLabel)
                    .addComponent(errorLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login_btn)
                .addGap(47, 47, 47)
                .addGroup(LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasAccountLabel)
                    .addComponent(Register))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LOGO.setBackground(new java.awt.Color(100, 104, 122));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\logo.PNG")); // NOI18N

        javax.swing.GroupLayout LOGOLayout = new javax.swing.GroupLayout(LOGO);
        LOGO.setLayout(LOGOLayout);
        LOGOLayout.setHorizontalGroup(
            LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LOGOLayout.setVerticalGroup(
            LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGOLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layerbackLayout = new javax.swing.GroupLayout(layerback);
        layerback.setLayout(layerbackLayout);
        layerbackLayout.setHorizontalGroup(
            layerbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerbackLayout.createSequentialGroup()
                .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layerbackLayout.setVerticalGroup(
            layerbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layerback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layerback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(920, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void EmailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        try {
            con.login(EmailF.getText(), String.valueOf(passField.getPassword()));
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Login_btnActionPerformed

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        
    }//GEN-LAST:event_formAncestorResized

    private void LoginBackgroundAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_LoginBackgroundAncestorResized

    }//GEN-LAST:event_LoginBackgroundAncestorResized

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked
        RegisterForm Register = new RegisterForm(con);
        Register.setVisible(true);
        Register.pack();
        Register.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_RegisterMouseClicked

    private void EmailFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailFMouseClicked
        clearText();
    }//GEN-LAST:event_EmailFMouseClicked

    private void EmailFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailFKeyTyped
        clearText();
    }//GEN-LAST:event_EmailFKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailF;
    private javax.swing.JLabel EmailIconLabel;
    private javax.swing.JPanel LOGO;
    private javax.swing.JPanel LoginBackground;
    private javax.swing.JLabel LoginFormLabel;
    private javax.swing.JLabel LoginFormLabel1;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel errorLabelEmail;
    private javax.swing.JLabel hasAccountLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel layerback;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passIconLabel;
    // End of variables declaration//GEN-END:variables
    
    //custom
    private void clearText()
    {
        if("Enter your email or username".equals(EmailF.getText()))
        {
            EmailF.setText("");
        }
    }
}
