/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.sample;


public class RegisterForm extends javax.swing.JFrame {
    public databaseConnection con;
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm(databaseConnection con) {
        this.con = con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        RegisterBtn = new javax.swing.JButton();
        hasAccountLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        errorLabelpass = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        EmailF = new javax.swing.JTextField();
        passIconLabel = new javax.swing.JLabel();
        UserIconLabel = new javax.swing.JLabel();
        RegisterFormLabel = new javax.swing.JLabel();
        IlearnIcon = new javax.swing.JLabel();
        userF = new javax.swing.JTextField();
        passF = new javax.swing.JPasswordField();
        confirmPasslabel = new javax.swing.JLabel();
        EmailIconLabel1 = new javax.swing.JLabel();
        errorExist1 = new javax.swing.JLabel();
        errorErrorExist2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 104, 122));

        registerPanel.setBackground(new java.awt.Color(51, 51, 51));

        RegisterBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBtnMouseClicked(evt);
            }
        });
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        hasAccountLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        hasAccountLabel.setForeground(new java.awt.Color(184, 184, 184));
        hasAccountLabel.setText("I have an account!");

        backBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 51, 102));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        backBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backBtnKeyPressed(evt);
            }
        });

        errorLabelpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        errorLabelpass.setForeground(new java.awt.Color(164, 33, 39));
        errorLabelpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabelpass.setText("Password is not the same!");

        passField.setBackground(new java.awt.Color(102, 102, 102));
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setToolTipText("");
        passField.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 6, 5, 6, new java.awt.Color(102, 102, 102)));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });

        EmailF.setBackground(new java.awt.Color(102, 102, 102));
        EmailF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EmailF.setForeground(new java.awt.Color(184, 184, 184));
        EmailF.setText("Enter username");
        EmailF.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 6, 5, 6, new java.awt.Color(102, 102, 102)));
        EmailF.setCaretPosition(0);
        EmailF.setDragEnabled(true);
        EmailF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailFMouseClicked(evt);
            }
        });
        EmailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFActionPerformed(evt);
            }
        });

        passIconLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        passIconLabel.setForeground(new java.awt.Color(184, 184, 184));
        passIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\key.png")); // NOI18N
        passIconLabel.setText("Password:");

        UserIconLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        UserIconLabel.setForeground(new java.awt.Color(184, 184, 184));
        UserIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\email.png")); // NOI18N
        UserIconLabel.setText("Username:");

        RegisterFormLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        RegisterFormLabel.setForeground(new java.awt.Color(184, 184, 184));
        RegisterFormLabel.setText("Register ");

        IlearnIcon.setBackground(new java.awt.Color(100, 104, 125));
        IlearnIcon.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        IlearnIcon.setForeground(new java.awt.Color(100, 78, 199));
        IlearnIcon.setText("STYLISHPEND");

        userF.setBackground(new java.awt.Color(102, 102, 102));
        userF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        userF.setForeground(new java.awt.Color(184, 184, 184));
        userF.setText("Enter your email");
        userF.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 6, 5, 6, new java.awt.Color(102, 102, 102)));
        userF.setCaretPosition(0);
        userF.setDragEnabled(true);
        userF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userFMouseClicked(evt);
            }
        });
        userF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFActionPerformed(evt);
            }
        });

        passF.setBackground(new java.awt.Color(102, 102, 102));
        passF.setForeground(new java.awt.Color(255, 255, 255));
        passF.setToolTipText("");
        passF.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 6, 5, 6, new java.awt.Color(102, 102, 102)));
        passF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFActionPerformed(evt);
            }
        });

        confirmPasslabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        confirmPasslabel.setForeground(new java.awt.Color(184, 184, 184));
        confirmPasslabel.setText("ConfirmPassword: ");

        EmailIconLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EmailIconLabel1.setForeground(new java.awt.Color(184, 184, 184));
        EmailIconLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\email.png")); // NOI18N
        EmailIconLabel1.setText("Email:");

        errorExist1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        errorExist1.setForeground(new java.awt.Color(164, 33, 39));
        errorExist1.setText("Already Exist!");

        errorErrorExist2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        errorErrorExist2.setForeground(new java.awt.Color(164, 33, 39));
        errorErrorExist2.setText("Already Exist!");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserIconLabel)
                            .addComponent(RegisterFormLabel)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addComponent(EmailIconLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(errorExist1)))
                        .addGap(13, 13, 13))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(errorErrorExist2)
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(registerPanelLayout.createSequentialGroup()
                                                .addComponent(hasAccountLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(backBtn))
                                            .addComponent(passIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(140, 140, 140)))
                                .addComponent(EmailF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(registerPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(confirmPasslabel)
                                    .addGap(27, 27, 27)
                                    .addComponent(errorLabelpass))))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(IlearnIcon)
                        .addGap(79, 79, 79))))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(IlearnIcon)
                .addGap(12, 12, 12)
                .addComponent(RegisterFormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailIconLabel1)
                    .addComponent(errorExist1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorErrorExist2)
                .addGap(4, 4, 4)
                .addComponent(passIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasslabel)
                    .addComponent(errorLabelpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterBtn)
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasAccountLabel)
                    .addComponent(backBtn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LordD\\Documents\\NetBeansProjects\\sample\\src\\main\\java\\com\\company\\icon\\logo.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void EmailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFActionPerformed

    private void userFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFActionPerformed

    private void passFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFActionPerformed

    private void backBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backBtnKeyPressed
    }//GEN-LAST:event_backBtnKeyPressed

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        LoginPage Login = new LoginPage(con);
        Login.setVisible(true);
        Login.pack();
        Login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void RegisterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnMouseClicked

    private void userFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userFMouseClicked
        if("Enter your email".equals(userF.getText()))
        {
            userF.setText("");
        }
    }//GEN-LAST:event_userFMouseClicked

    private void EmailFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailFMouseClicked
        if("Enter username".equals(EmailF.getText()))
        {
            EmailF.setText("");
        }
    }//GEN-LAST:event_EmailFMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailF;
    private javax.swing.JLabel EmailIconLabel1;
    private javax.swing.JLabel IlearnIcon;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel RegisterFormLabel;
    private javax.swing.JLabel UserIconLabel;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel confirmPasslabel;
    private javax.swing.JLabel errorErrorExist2;
    private javax.swing.JLabel errorExist1;
    private javax.swing.JLabel errorLabelpass;
    private javax.swing.JLabel hasAccountLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passF;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passIconLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField userF;
    // End of variables declaration//GEN-END:variables

    // Custom methods
    
}
